[package]
name = "tracing-metrics"
version = "0.1.0"
authors = ["Jon Gjengset <jon@thesquareplanet.com>"]
edition = "2018"

[dependencies]
tokio-trace-core = { git = "https://github.com/tokio-rs/tokio.git" }
hdrhistogram = "6.3"
slab = "0.4"
quanta = "0.3"
fnv = "1"
crossbeam = "0.7"
