[package]
name = "tracing-timing"
version = "0.4.2"
edition = "2018"
authors = ["Jon Gjengset <jon@thesquareplanet.com>"]

license = "MIT"

readme = "README.md"
description = "Inter-event timing metrics on top of tracing."
repository = "https://github.com/jonhoo/tracing-timing.git"

keywords = ["perf", "tracing", "profiling"]
categories = ["development-tools::profiling", "visualization"]

[badges]
azure-devops = { project = "jonhoo/jonhoo", pipeline = "tracing-timing", build = "13" }
cirrus-ci = { repository = "jonhoo/tracing-timing" }
codecov = { repository = "jonhoo/tracing-timing", branch = "master", service = "github" }
maintenance = { status = "experimental" }

[features]
layer = ["tracing-subscriber"]
default = []

[dependencies]
tracing-core = "0.1.2"
hdrhistogram = "7"
slab = "0.4"
quanta = "0.3"
fxhash = "0.2"
crossbeam = "0.7"
indexmap = "1.0"
doc-comment = "0.3"
tracing-subscriber = { version = "0.2.0", optional = true }

[dev-dependencies]
tracing = "0.1.2"
rand = "0.7"
rand_distr = "0.2.1"

[profile.release]
debug = true
