[package]
name = "tracing-timing"
version = "0.1.0"
authors = ["Jon Gjengset <jon@thesquareplanet.com>"]
edition = "2018"

[dependencies]
tracing-core = { git = "https://github.com/tokio-rs/tracing.git" }
hdrhistogram = "6.3.3"
slab = "0.4"
quanta = "0.3"
fxhash = "0.2"
crossbeam = "0.7"

[dev-dependencies]
tracing = { git = "https://github.com/tokio-rs/tracing.git" }
rand = "0.6"

[profile.release]
debug = true
